BackEnd/Miles/Miles.App/Areas/Admin/Controllers/SocialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Miles.Core.Entities;
using Miles.Data.Context;
using Miles.Service.Dtos.Socials;
using Miles.Service.Services.Interfaces;
using System.Security.Claims;

namespace Miles.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class SocialController : Controller
    {
        private readonly ISocialService _service;
        private readonly ILogger<SocialController> _logger;
        private readonly IStaffService _staffService;
        public SocialController(ISocialService service, ILogger<SocialController> logger, IStaffService staffService)
        {
            _service = service;
            _logger = logger;
            _staffService = staffService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var result = await _service.GetAllAsync(0, 0);
            int TotalCount = ((IEnumerable<Social>)result.items).Count();
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)TotalCount / 8);
            ViewBag.CurrentPage = page;
            int count = 8;
            result = await _service.GetAllAsync(count,page);
            return View(result.items);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var result = await _staffService.GetAllAsync(0, 0);
			ViewBag.Staffs = result.items;
			return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SocialPostDto dto)
        {
            var result = await _staffService.GetAllAsync(0, 0);
            ViewBag.Staffs = result.items;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }
             result = await _service.CreateAsync(dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Social Created by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _staffService.GetAllAsync(0, 0);
            ViewBag.Staffs = result.items;

             result = await _service.GetAsync(id);
            if (result.StatusCode == 404)
            {
                return NotFound();
            }
            return View(result.items);
        }
        public async Task<IActionResult> Update(int id,SocialUpdateDto dto)
        {
            var result = await _staffService.GetAllAsync(0, 0);
            ViewBag.Staffs = result.items;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            result = await _service.UpdateAsync(id,dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Social Updated by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _service.RemoveAsync(id);
            if(result.StatusCode == 404)
            {
                return NotFound();
            }
            _logger.LogInformation("Social Removed by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
    }
}

BackEnd/Miles/Miles.App/Areas/Admin/Controllers/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Miles.Core.Entities;
using Miles.Data.Context;
using Miles.Service.Dtos.Staffs;
using Miles.Service.Services.Interfaces;
using System.Security.Claims;

namespace Miles.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class StaffController : Controller
    {
        private readonly IStaffService _service;
        private readonly IPositionService _positionService;
        private readonly ILogger<StaffController> _logger;
        private readonly ISocialService _socialService;
        public StaffController(IStaffService service, ILogger<StaffController> logger, IPositionService positionService, ISocialService socialService)
        {
            _service = service;
            _logger = logger;
            _positionService = positionService;
            _socialService = socialService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var result = await _service.GetAllAsync(0, 0);
            int TotalCount = ((IEnumerable<Staff>)result.items).Count();
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)TotalCount / 4);
            ViewBag.CurrentPage = page;
            int count = 8;
            result = await _service.GetAllAsync(count,page);
            return View(result.items);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var result = await _positionService.GetAllAsync(0,0);
			ViewBag.Positions = result.items;
			return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(StaffPostDto dto)
        {
            var result = await _positionService.GetAllAsync(0, 0);
            ViewBag.Positions = result.items;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }
             result = await _service.CreateAsync(dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Staff Created by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _positionService.GetAllAsync(0, 0);
            ViewBag.Positions = result.items;

             result = await _service.GetAsync(id);
            if (result.StatusCode == 404)
            {
                return NotFound();
            }
            return View(result.items);
        }
        public async Task<IActionResult> Update(int id,StaffUpdateDto dto)
        {
            var result = await _positionService.GetAllAsync(0, 0);
            ViewBag.Positions = result.items;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }
             result = await _service.UpdateAsync(id,dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Staff Updated by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _service.RemoveAsync(id);
            if(result.StatusCode == 404)
            {
                return NotFound();
            }
            _logger.LogInformation("Staff Removed by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Social(int id)
        {
            var result = await _socialService.GetAllAsync(0, 0);
            IEnumerable<Social> socials =((IEnumerable<Social>)result.items).Where(x=>!x.IsDeleted && x.StaffId==id);
            return View(socials);
        }
    }
}

BackEnd/Miles/Miles.App/Areas/Admin/Views/Staff/Create.cshtml
@model StaffPostDto
<div class="container">
	<form method="post" enctype="multipart/form-data">
		<div class="text text-danger" asp-validation-summary="ModelOnly"></div>
	<div class="form-group">
			<label asp-for="FullName">FullName:</label>
			<input type="text" class="form-control" asp-for="FullName" />
			<span asp-validation-for="FullName" class="text text-danger"></span>
	</div>
		<div class="form-group">
			<label asp-for="Info">Info:</label>
			<input type="text" class="form-control" asp-for="Info" />
			<span asp-validation-for="Info" class="text text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="PositionId">Position</label>
			<select asp-for="PositionId" class="form-select" aria-label="Default select example">
				@foreach (var item in ViewBag.Positions)
				{
					<option value="@item.Id">@item.Name</option>
				}
			</select>
			<span asp-validation-for="PositionId" class="text text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="@Model.file">Photo:</label>
			<input type="file" class="form-control" asp-for="@Model.file" />
			<span asp-validation-for="file" class="text text-danger"></span>
		</div>
			@Html.AntiForgeryToken()
		<button type="submit" style="width:100%; " class="btn btn-outline-dark">Create</button>
	</form>
</div>

BackEnd/Miles/Miles.App/Areas/Admin/Views/Staff/Index.cshtml
@model IEnumerable<Staff>
<div class="container">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name:</th>
                <th scope="col">Position:</th>
                <th scope="col" class="text-center">Photo:</th>
                <th scope="col" class="text-center">Show && Add Social</th>
                <th scope="col" class="text-center">Update</th>
                <th scope="col" class="text-center">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <th>@item.FullName</th>
                    <th>@item.Position.Name</th>
                    <th class="text-center"><img style="width:100px;height:100px;border-radius:50%" src="~/Images/Staffs/@item.Image" /></th>
                    <td class="text-center" >
                        <a asp-controller="Staff" asp-action="social"  asp-route-id="@item.Id" style="margin-right: 25px;text-decoration:none">
                            <i class="fa-solid fa-eye text text-secondary"></i>
                        </a>
                        <a asp-controller="Social" asp-action="create" >
                            <i class="fa-solid fa-share-nodes text text-warning"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a asp-controller="Staff" asp-action="update" asp-route-id="@item.Id">
                            <i class="fas fa-edit text text-primary"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a onclick="if(!confirm('Are you sure?')){return false;}"
                           asp-controller="Staff" asp-action="remove" asp-route-id="@item.Id"
                           class=" delete-item"><i class="fas fa-trash text text-danger"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <ul class="pagination">
        <li><a class=" page-link" asp-controller="Staff" asp-action="index" asp-route-page="1">«</a></li>
        @for (int i = 1; i <= ViewBag.TotalPage; i++)
        {
            @if (i == ViewBag.CurrentPage)
            {
                <li class="page-item active"><a class=" page-link" asp-controller="Staff" asp-action="index" asp-route-page="@i">@i</a></li>
            }
            else
            {
                <li class="page-item"><a class=" page-link" asp-controller="Staff" asp-action="index" asp-route-page="@i">@i</a></li>
            }
        }
        <li><a class="page-link" asp-controller="Staff" asp-action="index" asp-route-page="@ViewBag.TotalPage">»</a></li>
    </ul>
    <div>
        <a asp-controller="Staff" asp-action="create" style="display: block; text-decoration: none; color: white; width: 100%; height: 100%" a>
            <div style="width:100%; " class="btn btn-outline-success">Create Staff </div>
        </a>
    </div>
</div>

BackEnd/Miles/Miles.App/Areas/Admin/Views/Staff/Social.cshtml
@model IEnumerable<Social>
<div class="container">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Staff Name:</th>
                <th scope="col">Name:</th>
                <th scope="col">Link:</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                    <tr>
                    <th scope="row">@item.Id</th>
                    @if (item.StaffId == null)
                    {
                        <th scope="row">Setting</th>
                    }
                    else
                    {
                        <th scope="row">@item.Staff?.FullName</th>
                    }
                        <th>@item.Icon</th>
                    <th>@item.Link</th>
                        <td><a asp-controller="social" asp-action="update" asp-route-id="@item.Id" >
                            <i class="fas fa-edit text text-primary"></i></a></td>
                        <td><a onclick="if(!confirm('Are you sure?')){return false;}"
                           asp-controller="social" asp-action="remove" asp-route-id="@item.Id"
                            class=" delete-item" ><i class="fas fa-trash text text-danger"></i></a></td>
                    </tr>
            }
        </tbody>
    </table>
    <div>
        <a asp-controller="Staff" asp-action="index" style="display: block; text-decoration: none; color: white; width: 100%; height: 100%" a>
            <div style="width:100%; " class="btn btn-outline-danger">Go Back</div></a>
    </div>
</div>

BackEnd/Miles/Miles.App/Areas/Admin/Views/Staff/Update.cshtml
@model StaffUpdateDto
<div class="container">
	<form method="post" enctype="multipart/form-data">
		<div class="text text-danger" asp-validation-summary="ModelOnly"></div>
		<div class="form-group">
			<label asp-for="FullName">Name:</label>
			<input type="text" class="form-control" asp-for="FullName" />
			<span asp-validation-for="FullName" class="text text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Info">Info:</label>
			<input type="text" class="form-control" asp-for="Info" />
			<span asp-validation-for="Info" class="text text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="PositionId">Position</label>
			<select asp-for="PositionId" class="form-select" aria-label="Default select example">
				<option value="0">Choose one of them</option>
				@foreach (var item in ViewBag.Positions)
				{
					if (Model.PositionId != null)
					{
						if (Model.PositionId == item.Id)
						{
							<option selected value="@item.Id">@item.Name</option>
							continue;
						}
					}
					<option value="@item.Id">@item.Name</option>
				}
			</select>
			<span asp-validation-for="PositionId" class="text text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="@Model.file">Photo:</label>
			<input type="file" class="form-control" asp-for="@Model.file" />
			<span asp-validation-for="file" class="text text-danger"></span>
		</div>
		@Html.AntiForgeryToken()
		<button type="submit" style="width:100%; " class="btn btn-outline-dark">Update</button>
	</form>
</div>