BackEnd/Miles/Miles.App/Areas/Admin/Controllers/PositionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Miles.Core.Entities;
using Miles.Data.Context;
using Miles.Service.Dtos.Categories;
using Miles.Service.Dtos.Positions;
using Miles.Service.Services.Interfaces;
using System.Security.Claims;

namespace Miles.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class PositionController : Controller
    {
        private readonly IPositionService _service;
        private readonly ILogger<PositionController> _logger;
        public PositionController( IPositionService service, ILogger<PositionController> logger)
        {
            _service = service;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var result = await _service.GetAllAsync(0, 0);
            int TotalCount = ((IEnumerable<Position>)result.items).Count();
            ViewBag.TotalPage = (int)Math.Ceiling((decimal)TotalCount / 8);
            ViewBag.CurrentPage = page;
            int count = 8;
            result = await _service.GetAllAsync(count,page);
            return View(result.items);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PositionPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            var result = await _service.CreateAsync(dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Position Created by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _service.GetAsync(id);
            if (result.StatusCode == 404)
            {
                return NotFound();
            }
            return View(result.items);
        }
        public async Task<IActionResult> Update(int id,PositionUpdateDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            var result = await _service.UpdateAsync(id,dto);
            if (result.StatusCode == 400)
            {
                ModelState.AddModelError("", result.Description);
                return View(dto);
            }
            _logger.LogInformation("Position Updated by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Remove(int id)
        {
            var result = await _service.RemoveAsync(id);
            if(result.StatusCode == 404)
            {
                return NotFound();
            }
            _logger.LogInformation("Position Removed by " + User.FindFirstValue(ClaimTypes.NameIdentifier));
            return RedirectToAction(nameof(Index));
        }
    }
}

BackEnd/Miles/Miles.App/Areas/Admin/Views/Position/Create.cshtml
@model PositionPostDto

<div class="container">
	<form method="post" enctype="multipart/form-data">
		<div class="text text-danger" asp-validation-summary="ModelOnly"></div>
	<div class="form-group">
		    <label asp-for="Name" >Name:</label>
			<input type="text" class="form-control" asp-for="Name" />
			<span asp-validation-for="Name" class="text text-danger"></span>
	</div>
			@Html.AntiForgeryToken()
		<button type="submit" style="width:100%; " class="btn btn-outline-dark">Create</button>
	</form>
</div>

BackEnd/Miles/Miles.App/Areas/Admin/Views/Position/Index.cshtml
@model IEnumerable<Position>
<div class="container">
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Name:</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Id</th>
                    <th>@item.Name</th>
                    <td>
                        <a asp-controller="Position" asp-action="update" asp-route-id="@item.Id">
                            <i class="fas fa-edit text text-primary"></i>
                        </a>
                    </td>
                    <td>
                        <a onclick="if(!confirm('Are you sure?')){return false;}"
                           asp-controller="Position" asp-action="remove" asp-route-id="@item.Id"
                           class=" delete-item"><i class="fas fa-trash text text-danger"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <ul class="pagination">
        <li><a class=" page-link" asp-controller="Position" asp-action="index" asp-route-page="1">«</a></li>
        @for (int i = 1; i <= ViewBag.TotalPage; i++)
        {
            @if (i == ViewBag.CurrentPage)
            {
                <li class="page-item active"><a class=" page-link" asp-controller="Position" asp-action="index" asp-route-page="@i">@i</a></li>
            }
            else
            {
                <li class="page-item"><a class=" page-link" asp-controller="Position" asp-action="index" asp-route-page="@i">@i</a></li>
            }
        }
        <li><a class="page-link" asp-controller="Position" asp-action="index" asp-route-page="@ViewBag.TotalPage">»</a></li>
    </ul>
    <div>
        <a asp-controller="Position" asp-action="create" style="display: block; text-decoration: none; color: white; width: 100%; height: 100%" a>
            <div style="width:100%; " class="btn btn-outline-success">Create Position </div>
        </a>
    </div>
</div>

BackEnd/Miles/Miles.App/Areas/Admin/Views/Position/Update.cshtml
@model PositionUpdateDto

<div class="container">
	<form method="post" enctype="multipart/form-data">
		<div class="text text-danger" asp-validation-summary="ModelOnly"></div>
	<div class="form-group">
		    <label asp-for="Name" >Name:</label>
			<input type="text" class="form-control" asp-for="Name" />
			<span asp-validation-for="Name" class="text text-danger"></span>
	</div>
			@Html.AntiForgeryToken()
		<button type="submit" style="width:100%; " class="btn btn-outline-info">Update</button>
	</form>
</div>